package com.wudi.facegate.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wudi.facegate.greenDao.Person;
import com.wudi.facegate.greenDao.Record;

import com.wudi.facegate.greenDao.PersonDao;
import com.wudi.facegate.greenDao.RecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig recordDaoConfig;

    private final PersonDao personDao;
    private final RecordDao recordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Record.class, recordDao);
    }
    
    public void clear() {
        personDaoConfig.clearIdentityScope();
        recordDaoConfig.clearIdentityScope();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

}
